### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by dcousens** [StevenLooman/mocha-lcov-reporter#11]
Is there any reason this repository isn't at `1.0.0`?

**Comment by StevenLooman** [comment]
Thank you for the issue. Is there a reason why it should be at `1.0.0`? Releasing a new version would produce a duplicate version, causing confusion.

**Comment by dcousens** [comment]
@StevenLooman the API has stabilized no?
Typically packages that are `0.y.z` are recognized as unstable.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by dcousens** [comment]
ping @StevenLooman

**Comment by StevenLooman** [comment]
@dcousens Sorry, this went out of my scope. I've just release 1.0.0, commit: 0ead2ec66f01c9392f9ed68591cea8e80ffafb8d.

**Comment by dcousens** [comment]
Thanks @StevenLooman !
