### ISSUE TITLE
LCov Reporter's strict dependence on a coverage tool

### ISSUE THREAD

**Issue by prometheansacrifice** [StevenLooman/mocha-lcov-reporter#12]
`mocha-lcov-reporter` strictly depends on a cover tool and hence fallback to empty object [here](https://github.com/StevenLooman/mocha-lcov-reporter/blob/master/lib/lcov.js#L21) must be avoided.

```
 var cov = g._$jscoverage || {};
```
When invoked without a coverage tool, it must warn.

**Comment by StevenLooman** [comment]
Thank you for this issue. This is helpful when no output is given, perhaps the cause of #14.

**Comment by mathiasrw** [comment]
:+1:

**Comment by StevenLooman** [comment]
Just released `mocha-lcov-reporter` `1.2.0`

**Comment by prometheansacrifice** [comment]
Awesome! Thanks @StevenLooman
