### ISSUE TITLE
With a small change this can work with Blanket as well as JSCoverage.

### ISSUE THREAD

**Issue by xelah1** [StevenLooman/mocha-lcov-reporter#13]
Changing this:
  var cov = g._$jscoverage || {};
to:
  var cov = g._$jscoverage || g._$blanket || {};

appears to be enough to generate coverage output using Blanket instead of JSCoverage. Blanket requires no pre-compilation step.

The output in my test case appears the same, except that blanket counts two extra lines as covered ('function blah(....) {' lines) and it produces an absolute file:/ URL instead of a relative file path.

**Comment by StevenLooman** [comment]
Will the file:// URL break anything?

Otherwise, it seems like a good idea.

**Comment by xelah1** [comment]
Looks like genhtml from lcov doesn't like the file:// - but it works once I remove it using perl/sed.

I'm using mocha-phantomjs to run simulated-browser-based tests in a .html file, and not testing node.js code. I tried running a simple test directly from mocha and it produced results without the 'file://' (and with an absolute path).

**Comment by StevenLooman** [comment]
Version 1.1.0 was just released. It should add support for [Blanket.js](http://blanketjs.org/).
