### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by mathiasrw** [StevenLooman/mocha-lcov-reporter#14]
While I do get expected test result from

```
node_modules/.bin/mocha -R dot
```

I get no output from

```
node_modules/.bin/mocha -R mocha-lcov-reporter
```

Its simply not spitting anything out. It takes about the same time as `-R dot` to run and If I `console.log` from a test file it gets printed - so tests are running.

Can it be because I am using npm 3?

**Comment by StevenLooman** [comment]
Thank you for the bug report. Can you provide more information? Perhaps a (completely) stripped down version of your project, containing a `package.json`, a single/minimal source file, and a single test, reproducing the problem.

My first guess would be that your source code isn't instrumented by `jscover` or `node-jscoverage`. The code needs to be instrumented to record how many times each line is executed, thus providing coverage data. If no coverage data is found, no output is generated. See the README in this repository.

A nice feature would be that this case is actually reported. An issue is already created for this: #12.

**Comment by mathiasrw** [comment]
> My first guess would be that your source code isn't instrumented by jscover or node-jscoverage

Its not - I did not understand that this was needed. Ill close the issue and try to read your documentation better and try to set it up again
