### ISSUE TITLE
Is there a way to load the lcov data inside webstorm?

### ISSUE THREAD

**Issue by DinisCruz** [StevenLooman/mocha-lcov-reporter#6]
I am using HTMLCov at the moment but it would be much better if I could see that data inside WebStorm

Note: I asked a similar question at SO http://stackoverflow.com/questions/27736710/how-to-open-jscoverage-results-inside-webstorm

**Comment by StevenLooman** [comment]
Thank you for the issue. This seems more of a WebStorm issue than a mocha-lcov-reporter issue. Your best shot is probably to open a ticket a their [support site](https://intellij-support.jetbrains.com/home). I'm closing the issue in this tracker.

Nevertheless, by looking through the manual I was not able to find anything useful. It all seems to rely on either Karma or JSTestDriver. Perhaps you can create a script which pretends to be Karma (i.e., takes the flags Karma takes etc,) but which generates the lcov data/file(s) using your own tests. Be ware though, things will probably get ugly.
